module.exports = sucursales = [
	{ sucursalID: "CC0101", sucursal: "Mercado Central" },
	{ sucursalID: "CC0201", sucursal: "Posadas" },
	{ sucursalID: "CC0301", sucursal: "Trelew" },
	{ sucursalID: "CC0401", sucursal: "Isidro Casanova" },
	{ sucursalID: "CC0501", sucursal: "San Martin" },
	{ sucursalID: "CC0701", sucursal: "Barracas" },
	{ sucursalID: "CC0901", sucursal: "Neuquen" },
	{ sucursalID: "CC1001", sucursal: "Junin" },
	{ sucursalID: "CC1101", sucursal: "Bahia Blanca" },
	{ sucursalID: "CC1201", sucursal: "La Rioja" },
	{ sucursalID: "CC1301", sucursal: "Pilar" },
	{ sucursalID: "CC1501", sucursal: "Berazategui" },
	{ sucursalID: "CC1601", sucursal: "Corrientes" },
	{ sucursalID: "CC1801", sucursal: "Pergamino" },
	{ sucursalID: "CC1901", sucursal: "Esquel" },
	{ sucursalID: "CC2001", sucursal: "Santa Rosa" },
	{ sucursalID: "CC2101", sucursal: "Comodoro Rivadavia" },
	{ sucursalID: "CC2201", sucursal: "9 de Julio" },
	{ sucursalID: "CC2301", sucursal: "Bariloche" },
	{ sucursalID: "CC2401", sucursal: "Lanus" },
	{ sucursalID: "CC2501", sucursal: "Pinamar" },
	{ sucursalID: "CC2601", sucursal: "Salta" },
	{ sucursalID: "CC2701", sucursal: "Villa Mercedes" },
	{ sucursalID: "CC2801", sucursal: "Zapala" },
	{ sucursalID: "CC2901", sucursal: "Moron" },
	{ sucursalID: "CC3001", sucursal: "Rio Gallegos" },
	{ sucursalID: "CC3101", sucursal: "Tandil" },
	{ sucursalID: "CC3201", sucursal: "Coronel Suarez" },
	{ sucursalID: "CC3301", sucursal: "Chascomus" },
	{ sucursalID: "CC3401", sucursal: "Viedma" },
	{ sucursalID: "CC3501", sucursal: "Concordia" },
	{ sucursalID: "CC3601", sucursal: "Parana" },
	{ sucursalID: "CC3701", sucursal: "Rio Grande" },
	{ sucursalID: "CC3801", sucursal: "Martinez" },
	{ sucursalID: "CC4101", sucursal: "Centro de Distribucion" },
	{ sucursalID: "CC4201", sucursal: "Caleta Olivia" },
	{ sucursalID: "CC4301", sucursal: "Roque Saenz Peña" },
	{ sucursalID: "CC4401", sucursal: "Calafate" },
	{ sucursalID: "CC4501", sucursal: "Santiago del Estero" },
	{ sucursalID: "CC4601", sucursal: "Cutral Co" },
	{ sucursalID: "CC4701", sucursal: "San Rafael" },
	{ sucursalID: "CC4801", sucursal: "Ushuaia" },
	{ sucursalID: "CC4901", sucursal: "Trenque Lauquen" },
	{ sucursalID: "CC6201", sucursal: "Tres Arroyos" },
	{ sucursalID: "CC6401", sucursal: "General Pico" },
	{ sucursalID: "CC6601", sucursal: "Lujan" },
	{ sucursalID: "CC6701", sucursal: "Piedrabuena" },
	{ sucursalID: "CC6801", sucursal: "El Bolson" },
	{ sucursalID: "CC6901", sucursal: "Venado Tuerto" },
	{ sucursalID: "CC7001", sucursal: "Pico Truncado" },
	{ sucursalID: "CC9401", sucursal: "Locales Pilar" },
	{ sucursalID: "CC9601", sucursal: "Ciudad Pyme" },
	{ sucursalID: "CC00S10", sucursal: "Administracion central ADM" },
]
